import Image from "next/image";
import MealSearchInput from "./components/MealSearchInput";

export const metadata = {
  title: "Meals",
  description: "Generated by create next app",
};

export default async function Meals({ searchParams }) {
  const search = searchParams?.search || "";
  let meals = [];

  try {
    const res = await fetch(
      `https://www.themealdb.com/api/json/v1/1/search.php?s=${search}`,
      { cache: "no-store" }
    );
    const data = await res.json();
    meals = data?.meals || [];
  } catch (error) {
    console.error(error);
  }

  return (
    <div>
      {/* search field */}
      <div>
        <MealSearchInput />
      </div>

      {/* cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-3">
        {meals.length > 0 ? (
          meals.map((meal, index) => (
            <div key={index} className="border p-2">
              <Image
                src={meal?.strMealThumb}
                width={641}
                height={641}
                alt={meal?.strMeal}
              />
              <p className="text-xl mb-3">{meal?.strMeal}</p>
              <p>{meal?.strInstructions}</p>
            </div>
          ))
        ) : (
          <p className="text-gray-500">No meals found.</p>
        )}
      </div>
    </div>
  );
}
